export const journalPrompts = {
  selfCare: [
    "Write about something that's been bothering you that you want to put behind you",
    "Write a letter forgiving yourself for something",
    "What would you tell a friend who was feeling the way you do right now?",
    "Describe a moment recently where you felt safe and comfortable",
    "Write about something you've been carrying that you're ready to set down",
    "What does your inner critic say, and what would your inner cheerleader say back?",
    "Write about a relationship that fills your cup",
    "What is your body trying to tell you right now?",
    "Write about a time you overcame something hard",
    "What do you wish someone would say to you today?",
    "Write about a small joy you almost missed",
    "What would a perfect self care day look like for you?",
  ],
  creativeWriting: [
    "You find a door in the woods that wasn't there yesterday. What's behind it?",
    "You wake up with the ability to speak to one type of animal. Which one and what do they tell you?",
    "Write about a library where every book is a life not yet lived",
    "A stranger hands you a map with no words on it. Where does it lead?",
    "You discover your reflection has been living a completely different life",
    "Write about the last wizard who remembers magic",
    "A letter arrives addressed to you, postmarked 100 years from now",
    "You find a small glowing stone on your doorstep. What does it do?",
    "Write about a city that exists only at night",
    "The moon sends you a message. What does it say?",
    "You can hear the thoughts of plants for one day",
    "Write about someone who collects lost things and the day they find something they weren't supposed to",
  ],
  goalSetting: [
    "What is one thing you want to accomplish this week?",
    "What does success look like to you?",
    "What habit do you want to build?",
    "What is holding you back from your goals?",
    "Where do you want to be in one year?",
    "What small step can you take today?",
    "What skill do you want to develop?",
    "What would you do if you knew you couldn't fail?",
    "What does your ideal routine look like?",
    "What are you working toward right now?",
    "What do you need to stop doing to move forward?",
    "Who do you want to become?",
  ],
  reflection: [
    "What did you learn about yourself this week?",
    "What are you proud of lately?",
    "What would you do differently if you could?",
    "How have you grown in the past year?",
    "What relationships are most important to you and why?",
    "What has been your biggest challenge recently?",
    "What moment from today do you want to remember?",
    "What patterns do you notice in your life?",
    "What are you avoiding and why?",
    "What does your gut tell you about a current situation?",
    "Who has influenced you most and how?",
    "What would your younger self think of you now?",
  ],
};
